### ISSUE TITLE
The instructions didn't work

### ISSUE THREAD

**Issue by yatesco** [davidgomes/bs-webworkers#2]
Hi, 

I followed the instructions in the readme but I get an error stating it can't `WebWorkers`.

Steps to reproduce:
- `create-react-app bs-webworkers-test --scripts-version reason-scripts`
- `yarn add bs-webworkers`
- add `bs-webworkers` as a dependency in `bsconfig.yml` 
- add `open WebWorkers;` to `src/app.re`  OR
- add `let worker = WebWorkers.create_webworker("worker.bs.js");` to `src/app.re`
- `yarn start`

And the following error appears:
```
./src/index.re
Module build failed: Error: We've found a bug for you!
  /Users/coliny/Dev/bs-webworkers-test/src/app.re 3:6-15
  
  1 │ [%bs.raw {|require('./app.css')|}];
  2 │ 
  3 │ open WebWorkers;
  4 │ 
  5 │ [@bs.module] external logo : string = "./logo.svg";
  
  The module or file WebWorkers can't be found.
  
  - If it's a third-party dependency:
    - Did you list it in bsconfig.json?
    - Did you run `bsb` instead of `bsb -make-world`
      (latter builds third-parties)?
  - Did you include the file's directory in bsconfig.json?    at <anonymous>
```

I have committed a repo following the above steps: https://github.com/yatesco/bs-webworkers-test.

I haven't got the first clue as to what I am doing with reasonml ;-) so it is entirely possible I missed an "obvious" step.

**Comment by davidgomes** [comment]
I am getting syntax errors in your demo repo in node_modules, so I can't really test it. Also, there were a couple of bugs in bs-webworkers that you are running into (related to my bsconfig.json) and so you should make sure you update to the latest version of bs-webworkers (0.2.4).

Also, that repository has **a lot** of files, so it will be hard to pinpoint what is going wrong.

Let's try something simpler:

1. `bsb -init my-first-app -theme basic-reason` (from the official Reason docs' [quickstart](https://reasonml.github.io/docs/en/quickstart-javascript.html))
2. `npm install --save bs-webworkers` (make sure you get at least 0.2.4)
3. Add `bs-webworkers` to the `bsconfig.json` (not YAML like you wrote):

```
…
  "bs-dependencies": [
    "bs-webworkers"
  ],
…
```

4. Edit the `demo.re` file and add `open WebWorkers;` and then everything will work.

Please let me know if the new version worked so we can close this issue.

**Comment by yatesco** [comment]
Hi David, yeah that repo was created from the react starter kick. 

I will try your bare-bones approach tomorrow and then close/update this.

Thanks!

**Comment by davidgomes** [comment]
You can also try to simply update your bs-webworkers dependency to 0.2.4 and then reinstall all packages (`rm -rf node_modules && npm install`). That might just do it.

**Comment by yatesco** [comment]
Sorry - this took me longer to get to, and apologies for the error in the original ticket. 

I followed your instructions (simplifying the project and upgrading to 0.2.4) but I now get another error:
```
➜  bs-webworkers-test git:(master) ✗ node src/demo.bs.js 
/Users/coliny/Dev/bs-webworkers-test/src/demo.bs.js:5
var worker = new Worker("worker.bs.js");
             ^

ReferenceError: Worker is not defined
    at Object.<anonymous> (/Users/coliny/Dev/bs-webworkers-test/src/demo.bs.js:5:14)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3

```

I have pushed the simplified demo to https://github.com/yatesco/bs-webworkers-test.

**Comment by davidgomes** [comment]
Hi! It's normal that that happens because Web Workers are only implemented in browsers. The outputted JavaScript file needs to be included in a browser environment (with a script tag).

**Comment by yatesco** [comment]
You are absolute correct @davidgomes, let me close this and thanks for your patience :-).
